#version: 2.1
#orbs:
  #aws-code-deploy: circleci/aws-code-deploy@0.0.10
#workflows:
 # deploy_application:
 #   jobs:
  #    - aws-code-deploy/deploy:
   #       application-name: Redwood
    #      deployment-group: RedwoodDeploy && goodworks
    #      service-role-arn: arn:aws:iam::801391952744:role/CodeDeployServiceRole-new
          #arn:aws:iam::801391952744:role/CodeDeployServiceRole
          #arn:aws:iam::801391952744:role/CodeDeployDemo-EC2-Instance-Profile
      #    bundle-bucket: angular-bucket-17
       #   bundle-source: Build/
       #   bundle-key: rbk

--- 
orbs: 
  aws-code-deploy: circleci/aws-code-deploy@0.0.10

version: 2.1
workflows: 
  deploy_application: 
    jobs: 
      - aws-code-deploy/deploy: 
          application-name: rbk-tco-backend-master
          bundle-bucket: tco-app
          bundle-key: tco-backend
          bundle-source: Build/
          deployment-group: rbk-tco-backend-dg-master
          service-role-arn: "arn:aws:iam::688687378425:role/CodeDeployEC2ServiceRole"
          filters: 
            branches: 
              only: master          
      - aws-code-deploy/deploy: 
          application-name: rbk-tco-backend
          bundle-bucket: tco-app
          bundle-key: tco-backend
          bundle-source: Build/
          deployment-group: rbk-tco-backend-dg
          service-role-arn: "arn:aws:iam::688687378425:role/CodeDeployEC2ServiceRole"
          filters: 
            branches: 
              only: qa
