#version: 2.1
#orbs:
  #aws-code-deploy: circleci/aws-code-deploy@0.0.10
#workflows:
 # deploy_application:
 #   jobs:
  #    - aws-code-deploy/deploy:
   #       application-name: Redwood
    #      deployment-group: RedwoodDeploy && goodworks
    #      service-role-arn: arn:aws:iam::801391952744:role/CodeDeployServiceRole-new
          #arn:aws:iam::801391952744:role/CodeDeployServiceRole
          #arn:aws:iam::801391952744:role/CodeDeployDemo-EC2-Instance-Profile
      #    bundle-bucket: angular-bucket-17
       #   bundle-source: Build/
       #   bundle-key: rbk

--- 
orbs: 
  aws-code-deploy: circleci/aws-code-deploy@0.0.10
workflows:
  deploy_application:
    jobs: 
      - aws-code-deploy/deploy: 
          application-name: demoapp-dev
          bundle-bucket: angular-bucket-17
          bundle-key: dev1
          bundle-source: Build/
          deployment-group: SimpleDemoDG
          service-role-arn: "arn:aws:iam::801391952744:role/CodeDeployServiceRole"
   
     - aws-code-deploy/deploy: 
         application-name: demoapp-qa
         bundle-bucket: myApplicationS3Bucket
         bundle-key: qa1
         bundle-source: Build/
         deployment-group: ~
         service-role-arn: "arn:aws:iam::801391952744:role/CodeDeployServiceRole"

workflows: 
  deploy_application: 
    jobs: 
     - aws-code-deploy/deploy:  
        filters: 
          branches: 
              only: master
     - aws-code-deploy/deploy: 
        filters: 
          branches: 
              only: build-issues
